# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unit.proto',
  package='unit',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nunit.proto\x12\x04unit\"?\n\x0e\x43onvertRequest\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\",\n\x0c\x43onvertReply\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x32=\n\x04Unit\x12\x35\n\x07\x43onvert\x12\x14.unit.ConvertRequest\x1a\x12.unit.ConvertReply\"\x00\x62\x06proto3')
)




_CONVERTREQUEST = _descriptor.Descriptor(
  name='ConvertRequest',
  full_name='unit.ConvertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='unit.ConvertRequest.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='unit.ConvertRequest.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='unit.ConvertRequest.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=83,
)


_CONVERTREPLY = _descriptor.Descriptor(
  name='ConvertReply',
  full_name='unit.ConvertReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='unit.ConvertReply.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='unit.ConvertReply.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['ConvertRequest'] = _CONVERTREQUEST
DESCRIPTOR.message_types_by_name['ConvertReply'] = _CONVERTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConvertRequest = _reflection.GeneratedProtocolMessageType('ConvertRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONVERTREQUEST,
  __module__ = 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.ConvertRequest)
  ))
_sym_db.RegisterMessage(ConvertRequest)

ConvertReply = _reflection.GeneratedProtocolMessageType('ConvertReply', (_message.Message,), dict(
  DESCRIPTOR = _CONVERTREPLY,
  __module__ = 'unit_pb2'
  # @@protoc_insertion_point(class_scope:unit.ConvertReply)
  ))
_sym_db.RegisterMessage(ConvertReply)



_UNIT = _descriptor.ServiceDescriptor(
  name='Unit',
  full_name='unit.Unit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=131,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='Convert',
    full_name='unit.Unit.Convert',
    index=0,
    containing_service=None,
    input_type=_CONVERTREQUEST,
    output_type=_CONVERTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNIT)

DESCRIPTOR.services_by_name['Unit'] = _UNIT

# @@protoc_insertion_point(module_scope)
