# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import unit_pb2 as unit__pb2


class UnitStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Convert = channel.unary_unary(
        '/unit.Unit/Convert',
        request_serializer=unit__pb2.ConvertRequest.SerializeToString,
        response_deserializer=unit__pb2.ConvertReply.FromString,
        )


class UnitServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Convert(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UnitServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Convert': grpc.unary_unary_rpc_method_handler(
          servicer.Convert,
          request_deserializer=unit__pb2.ConvertRequest.FromString,
          response_serializer=unit__pb2.ConvertReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'unit.Unit', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
